version: '3.9'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333" # Expose Qdrant on port 6333 of the host
    volumes:
      - qdrant_data:/qdrant/data # Persistent storage for Qdrant data
    environment:
      RUST_LOG: "info" # Set logging level to info

volumes:
  qdrant_data:
    name: qdrant_data

